image: gradle:alpine

default:
  tags:
    - shellocal

stages:
  - test

test:
  stage: test
  script:
  - ./gradlew clean test
  - ./gradlew allureReport
  artifacts:
    paths:
    - build/reports/allure-report/allureReport/*